<br><hr>
<center><h1> Agama Buddha</h1></center>
<hr>

	<p><h2><ol>
Agama Buddha atau Buddhisme adalah sebuah agama nonteistik atau filsafat <em>(Sanskrit: dharma; Pali: धम्म dhamma)<em> yang berasal dari anak benua India yang meliputi beragam tradisi, kepercayaan, dan praktik spiritual yang sebagian besar berdasarkan pada ajaran yang dikaitkan dengan Siddhartha Gautama, yang secara umum dikenal sebagai Sang Buddha (berarti "yang telah sadar"). Menurut tradisi Buddhis, Sang Buddha hidup dan mengajar di bagian timur anak benua India dalam beberapa waktu antara abad ke-6 sampai ke-4 SEU (Sebelum Era Umum). Dia dikenal oleh para umat Buddha sebagai seorang guru yang telah sadar atau tercerahkan yang membagikan wawasan-Nya untuk membantu makhluk hidup mengakhiri penderitaan mereka dengan melenyapkan ketidaktahuan/kebodohan/kegelapan batin <em>(moha)</em>, keserakahan <em>(lobha)</em>, dan kebencian/kemarahan <em>(dosa)</em>. Berakhirnya atau padamnya moha, lobha, dan dosa disebut dengan Nibbana. Untuk mencapai Nibbana seseorang melakukan perbuatan benar, tidak melakukan perbuatan salah, mempraktikkan meditasi untuk menjaga pikiran agar selalu pada kondisi yang baik atau murni dan mampu memahami fenomena batin dan jasmani.<br>
<br>
Dua aliran utama Buddhisme yang masih ada yang diakui secara umum oleh para ahli: Theravada ("Aliran Para Sesepuh") dan Mahayana ("Kendaraan Agung"). Vajrayana, suatu bentuk ajaran yang dihubungkan dengan siddha India, dapat dianggap sebagai aliran ketiga atau hanya bagian dari Mahayana. Theravada mempunyai pengikut yang tersebar luas di Sri Lanka, dan Asia Tenggara. Mahayana, yang mencakup tradisi Tanah Murni, Zen, Nichiren, Shingon, dan Tiantai (Tiendai) dapat ditemukan di seluruh Asia Timur. Buddhisme Tibet, yang melestarikan ajaran Vajrayana dari India abad ke-8[4], dipraktikkan di wilayah sekitar Himalaya, Mongolia, dan Kalmykia. Jumlah umat Buddha di seluruh dunia diperkirakan antara 488 juta dan 535 juta, menjadikannya sebagai salah satu agama utama dunia.<br>
<br>
Dalam Buddhisme Theravada, tujuan utamanya adalah pencapaian kebahagiaan tertinggi Nibbana, yang dicapai dengan mempraktikkan Jalan Mulia Berunsur Delapan (juga dikenal sebagai Jalan Tengah), sehingga melepaskan diri dari apa yang dinamakan sebagai siklus penderitaan dan kelahiran kembali. Buddhisme Mahayana, sebaliknya beraspirasi untuk mencapai kebuddhaan melalui jalan bodhisattva, suatu keadaan di mana seseorang tetap berada dalam siklus untuk membantu makhluk lainnya mencapai pencerahan.<br>
<br>
Setiap aliran Buddha berpegang kepada Tripitaka sebagai referensi utama karena dalamnya tercatat sabda dan ajaran Buddha Gautama. Pengikut-pengikutnya kemudian mencatat dan mengklasifikasikan ajarannya dalam tiga buku yaitu Sutta Piṭaka (khotbah-khotbah Sang Buddha), Vinaya Piṭaka (peraturan atau tata tertib para bhikkhu) dan Abhidhamma Piṭaka (ajaran hukum metafisika dan psikologi).<br>
<br>
Seluruh naskah aliran Theravada menggunakan bahasa Pali, yaitu bahasa yang dipakai di sebagian India (khususnya daerah Utara) pada zaman Sang Buddha. Cukup menarik untuk dicatat, bahwa tidak ada filsafat atau tulisan lain dalam bahasa Pali selain kitab suci agama Buddha Theravada, yang disebut kitab suci Tipitaka, oleh karenanya, istilah "ajaran agama Buddha berbahasa Pali" sinonim dengan agama Buddha Theravada. Agama Buddha Theravada dan beberapa sumber lain berpendapat, bahwa Sang Buddha mengajarkan semua ajaran-Nnya dalam bahasa Pali, di India, Nepal dan sekitarnya selama 45 tahun terakhir hidup-Nya, sebelum Dia mencapai Parinibbana.<br>
<br>
Seluruh naskah aliran Mahayana pada awalnya berbahasa Sansekerta dan dikenal sebagai Tripitaka. Oleh karena itu istilah agama Buddha berbahasa Sansekerta sinonim dengan agama Buddha Mahayana. Bahasa Sansekerta adalah bahasa klasik dan bahasa tertua yang dipergunakan oleh kaum terpelajar di India. Selain naskah agama Buddha Mahayana, kita menjumpai banyak catatan bersejarah dan agama, atau naskah filsafat tradisi setempat lainnya ditulis dalam bahasa Sansekerta.<br>
	</h2></ol></p>

<hr><br>